### ISSUE TITLE
Missing System.Net.HttpClient source

### ISSUE THREAD

**Issue by davidkeaveny** [microsoft/referencesource#75]
Is there a particular reason why System.Net.HttpClient does not appear in ReferenceSource? Its source is available at [dotnet/corefx](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs), but since it is not available at ReferenceSource, I am having major difficulties debugging [an issue that I have](https://stackoverflow.com/questions/52491660/httpclient-changing-request-uri-when-called-from-webapi) (where the `SendAsync` method changes the `request.RequestUri` when it shouldn't).

**Comment by elliott-beach** [comment]
Yaaaas, this should be available so I can understand exactly what operations are doing!

**Comment by karelz** [comment]
Seems that the full `Http` subdirectory is missing :( `ndp\fx\src\Net\System\Net\Http`

**Comment by IanKemp** [comment]
@karelz I'm pretty sure that reference source is no within your area of responsibility at MS, but given that issues filed in this repo seem to go nowhere, would you please consider taking it upon yourself to get this one, at least, resolved? Pretty please?

**Comment by karelz** [comment]
We started discussing that with the right people few weeks ago. And I used this +1 for another ping on action there. We will get to it.
While painful, I can't invest my personal time here yet - I've got higher priority things burning I need to take care of first, sorry.

**Comment by danmosemsft** [comment]
Fixed by https://github.com/Microsoft/referencesource/pull/105

This is not the same as being on source server, but you can manually point the debugger there.

**Comment by danmosemsft** [comment]
@rbhanda you can close this.

**Comment by cppcraze** [comment]
Hey Danmose, how is this issue fixed? 
try search referencesource now (FX 4.8)
https://referencesource.microsoft.com/#q=httpclient, httpclient still not there.

**Comment by danmosemsft** [comment]
@cppcraze the website is not autogenerated from the repo. Right now we don't have a plan to update the website as it's manually done. The goal is to share the source -- it can be found on https://github.com/microsoft/referencesource as in the PR linked above.

**Comment by danmosemsft** [comment]
@rbhanda can you please close this issue or better still give me permissions !
